AllCops:
  Exclude:
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/setup
    - bin/update
    - bin/webpack
    - bin/webpack-dev-server
    - bin/yarn
    - db/schema.rb
    - node_modules/**/*

# AbcSize:
#   Enabled: false

# ClassLength:
#   Enabled: false

# CyclomaticComplexity:
#   Enabled: false

Documentation:
  Enabled: false

# MethodLength:
#   Enabled: false

Metrics/LineLength:
  Enabled: false

# NumericLiterals:
#   MinDigits: 6

# PerceivedComplexity:
#   Enabled: false
