version: "3"

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    env_file:
      - .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/portfolio
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
  webpacker:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    env_file:
      - .env
    command: ./bin/webpack-dev-server
    volumes:
      - .:/portfolio
    ports:
      - "3035:3035"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
