version: "3"

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    env_file:
      - .env.prod
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.production
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - PORTFOLIO_DATABASE=${PORTFOLIO_DATABASE}
        - PORTFOLIO_DATABASE_USERNAME=${PORTFOLIO_DATABASE_USERNAME}
        - PORTFOLIO_DATABASE_PASSWORD=${PORTFOLIO_DATABASE_PASSWORD}
        - PORTFOLIO_DATABASE_HOST=${PORTFOLIO_DATABASE_HOST}
        - PORTFOLIO_DATABASE_PORT=${PORTFOLIO_DATABASE_PORT}
        - AWS_REGION=${AWS_REGION}
        - S3_BUCKET=${S3_BUCKET}
        - S3_ENDPOINT=${S3_ENDPOINT}
    env_file: .env.prod
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - web
    ports:
      - "80:80"
