development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: portfolio_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: portfolio_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

productuon:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: portfolio_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
