# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d09da2af597c006bdce0e80d171b2ca25a6958ec4a8f6731f03c5ddef38fc39c209eac2f071537fe6352d60fc759c85048c7f5e4639435b6961fdb0357e56d4

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: f14cf442f39671deffc124c06855ffcd71b9229d78ed9b57ecd9289ca15075f38d5a60fc4fd31b6b43765f92a645a5a389591446d789d365c882b17b363a315e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
